---
services:
  odoo:
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      PORT: 5432
    image: odoo:latest
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "8069:8069"
    volumes:
      - "./tests/resources/odoo.conf:/etc/odoo/odoo.conf"
      - "./tests/resources:/mnt/restore"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
      interval: 10s
      retries: 5
      start_period: 5s
