---
name: CI

on:
  push:
    branches-ignore:
      - 'feature/latest'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
